name: lint

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v9
        env:
          GOPRIVATE: buf.build
        with:
          version: v2.5
          args: --enable govet,staticcheck --enable-fmt gofmt